Add GitHub Actions
mathworks-continuous-integration/example-matlab pull request #2
Opened 2020-12-21 18:20 UTC by mcafaro

2020-12-22 19:13 UTC, mw-hrastega commented on README.md
> +| `.github/workflows/workflow.yml`     | The `workflow.yml` file defines the pipeline that runs on [GitHub&reg; Actions](https://github.com/matlab-actions).
1) Shouldn't we say workflow instead of pipeline? Pipeline isn't part of GitHub Actions terminology.
2) Because other links land on doc pages, the target of this link should be the README in the repo that @jwpereira is setting up.

2020-12-22 19:21 UTC, mw-hrastega commented on README.md
> +* Currently, MATLAB builds on CircleCI and Travis CI are available only for public projects. MATLAB builds on Azure DevOps and GitHub Actions that use Microsoft&reg;-hosted or GitHub-hosted agents ar
Consider summarizing "Microsoft®-hosted or GitHub-hosted" to "cloud-hosted".

2020-12-22 19:25 UTC, mw-hrastega commented on README.md
> +| `.github/workflows/workflow.yml`     | The `workflow.yml` file defines the pipeline that runs on [GitHub&reg; Actions](https://github.com/matlab-actions).
In the next section, we have this phrase: "Use these example pipeline YAMLs to:"

For GitHub actions, we have workflow YAMLs. To be more inclusive, how about saying "Use these example scripts to:"?

2020-12-22 19:26 UTC, mw-hrastega requested changes
Looks good. Some minor comments.

2020-12-23 18:17 UTC, mcafaro commented on README.md
> +| `.github/workflows/workflow.yml`     | The `workflow.yml` file defines the pipeline that runs on [GitHub&reg; Actions](https://github.com/matlab-actions).
I don't believe "pipeline" is part of Travis terminology either and means something slightly different on Circle. I thought we might be using it in a more general sense here. We could perhaps standardize on "configuration"?

2020-12-23 18:40 UTC, mw-hrastega commented on README.md
> +| `.github/workflows/workflow.yml`     | The `workflow.yml` file defines the pipeline that runs on [GitHub&reg; Actions](https://github.com/matlab-actions).
Thanks for the info. In this case, I think using pipeline in the general sense is totally fine :).

2020-12-23 18:57 UTC, mcafaro commented on README.md
> +* Currently, MATLAB builds on CircleCI and Travis CI are available only for public projects. MATLAB builds on Azure DevOps and GitHub Actions that use Microsoft&reg;-hosted or GitHub-hosted agents ar
Done

2020-12-23 19:43 UTC, mw-hrastega approved these changes

2021-01-05 18:41 UTC, merged